apiVersion: 1
datasources:
  - name: Speech Telemetry
    uid: speech-telemetry
    type: postgres
    access: proxy
    url: ${TELEMETRY_DATABASE_HOST}
    user: ${TELEMETRY_GRAFANA_USER}
    secureJsonData:
      password: ${TELEMETRY_GRAFANA_PASSWORD}
    jsonData:
      database: ${TELEMETRY_DATABASE}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
