#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

readonly LOCAL_IMAGE_REPOSITORY="speech-to-text-ubx330m"
readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
readonly MODEL_DIR="$PROJECT_DIR/models"
readonly CHECKOUT_UID="${SUDO_UID:-$(id -u)}"
readonly CHECKOUT_GID="${SUDO_GID:-$(id -g)}"
readonly INSTALL_DIR="$PROJECT_DIR/data/ubx330m"
readonly CACHE_DIR="$INSTALL_DIR/cache"
readonly HF_CACHE_DIR="$CACHE_DIR/huggingface"
readonly EXPORT_HOME_DIR="$CACHE_DIR/home"
readonly EXPORT_XDG_CACHE_DIR="$CACHE_DIR/xdg/cache"
readonly EXPORT_XDG_CONFIG_DIR="$CACHE_DIR/xdg/config"
readonly EXPORT_XDG_DATA_DIR="$CACHE_DIR/xdg/data"
readonly EXPORT_TMP_DIR="$CACHE_DIR/tmp"
readonly COMPOSE_PROJECT="speech_to_text_ubx330m"
readonly IMAGE_VERSION="${1:-${SPEECH_TO_TEXT_VERSION:-v0.1.3}}"
readonly EXPORT_DEPS_IMAGE="$LOCAL_IMAGE_REPOSITORY-export-deps:$IMAGE_VERSION"
readonly IMAGE="$LOCAL_IMAGE_REPOSITORY:$IMAGE_VERSION"

fail() {
  printf '%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command '$1' is not installed. No installation changes have been made."
}

ipv4_to_int() {
  local a b c d
  IFS=. read -r a b c d <<< "$1"
  printf '%s' "$(( (10#$a << 24) | (10#$b << 16) | (10#$c << 8) | 10#$d ))"
}

int_to_ipv4() {
  local value="$1"
  printf '%d.%d.%d.%d' \
    "$(( (value >> 24) & 255 ))" \
    "$(( (value >> 16) & 255 ))" \
    "$(( (value >> 8) & 255 ))" \
    "$(( value & 255 ))"
}

detect_lan() {
  local route address prefix route_field i
  local -a route_fields
  route=$(ip -4 route get 1.1.1.1 2>/dev/null | head -n1) || fail "Could not identify the host's LAN route."
  LAN_IP=""
  LAN_IF=""
  read -r -a route_fields <<< "$route"
  for ((i = 0; i < ${#route_fields[@]}; i++)); do
    route_field="${route_fields[$i]}"
    if [[ "$route_field" == "dev" && $((i + 1)) -lt ${#route_fields[@]} ]]; then
      LAN_IF="${route_fields[$((i + 1))]}"
    elif [[ "$route_field" == "src" && $((i + 1)) -lt ${#route_fields[@]} ]]; then
      LAN_IP="${route_fields[$((i + 1))]}"
    fi
  done
  [[ -n "$LAN_IP" && -n "$LAN_IF" ]] || fail "Could not identify the LAN IPv4 address and interface."
  if [[ "$LAN_IF" =~ ^(tailscale|wg|tun|tap|zt|vpn)[[:alnum:]_.-]*$ ]]; then
    fail "The selected route uses virtual VPN interface '$LAN_IF'; no physical LAN route was identified. Connect the host to its LAN and rerun."
  fi
  local ip_number cgnat_start cgnat_end private_start private_end
  ip_number=$(ipv4_to_int "$LAN_IP")
  cgnat_start=$(ipv4_to_int 100.64.0.0)
  cgnat_end=$(ipv4_to_int 100.127.255.255)
  if (( ip_number >= cgnat_start && ip_number <= cgnat_end )); then
    fail "The selected address $LAN_IP is in the shared CGNAT range; no physical LAN route was identified. Connect the host to its LAN and rerun."
  fi
  private_start=$(ipv4_to_int 10.0.0.0)
  private_end=$(ipv4_to_int 10.255.255.255)
  local is_private=0
  if (( ip_number >= private_start && ip_number <= private_end )); then
    is_private=1
  fi
  private_start=$(ipv4_to_int 172.16.0.0)
  private_end=$(ipv4_to_int 172.31.255.255)
  if (( ip_number >= private_start && ip_number <= private_end )); then
    is_private=1
  fi
  private_start=$(ipv4_to_int 192.168.0.0)
  private_end=$(ipv4_to_int 192.168.255.255)
  if (( ip_number >= private_start && ip_number <= private_end )); then
    is_private=1
  fi
  (( is_private == 1 )) || fail "The selected address $LAN_IP is not an RFC1918 private LAN address; no physical LAN route was identified. Connect the host to its LAN and rerun."

  address=$(ip -o -4 addr show dev "$LAN_IF" scope global | awk -v ip="$LAN_IP" '$4 ~ ("^" ip "/") { print $4; exit }')
  [[ -n "$address" ]] || fail "Could not determine the LAN subnet for $LAN_IP on $LAN_IF."
  prefix="${address#*/}"
  [[ "$prefix" =~ ^[0-9]+$ ]] && (( prefix >= 1 && prefix <= 32 )) || fail "The LAN interface has an invalid IPv4 prefix: $address"
  local mask ip_number network_number
  ip_number=$(ipv4_to_int "$LAN_IP")
  mask=$(( (0xffffffff << (32 - prefix)) & 0xffffffff ))
  network_number=$(( ip_number & mask ))
  LAN_SUBNET="$(int_to_ipv4 "$network_number")/$prefix"
}

port_is_free_or_owned() {
  local listeners id project saw_owned=0
  listeners=$(ss -H -ltn 'sport = :8000') || fail "Could not inspect TCP port 8000."
  if [[ -z "$listeners" ]]; then
    return 0
  fi

  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    while IFS= read -r id; do
      [[ -n "$id" ]] || continue
      project=$(docker inspect --format '{{ index .Config.Labels "com.docker.compose.project" }}' "$id" 2>/dev/null || true)
      [[ "$project" == "$COMPOSE_PROJECT" ]] || fail "TCP port 8000 is occupied by another service. Nothing was stopped or changed."
      saw_owned=1
    done < <(docker ps --filter publish=8000 --format '{{.ID}}')
  fi
  (( saw_owned == 1 )) || fail "TCP port 8000 is occupied. Nothing was stopped or changed."
}

simulate_apt_install() {
  local packages=("$@") simulation
  simulation=$(apt-get -s install --no-install-recommends "${packages[@]}" 2>&1) || fail "Ubuntu could not safely plan the Docker package installation. No packages were changed. Details: $simulation"
  if grep -Eq '^[[:space:]]*Remv[[:space:]]' <<< "$simulation"; then
    fail "Installing Ubuntu's Docker packages would remove an existing package. Nothing was changed. Resolve the package conflict manually, then rerun."
  fi
}

install_docker_if_needed() {
  local packages=()
  if (( EUID != 0 )); then
    if ! command -v docker >/dev/null 2>&1; then
      fail "Docker is missing. Run this installer as root to install Docker, or install Docker Engine and Compose first, then rerun as a user who can access Docker."
    fi
    docker info >/dev/null 2>&1 || fail "Docker is not running or this user cannot access it. Start Docker and grant this user access to the Docker socket (then sign in again); rerun as root only if host setup is needed."
    docker compose version >/dev/null 2>&1 || fail "Docker Compose is unavailable. Install the Compose plugin as root, then rerun."
    return 0
  fi
  if ! command -v docker >/dev/null 2>&1; then
    packages+=(docker.io)
  fi
  if ! docker compose version >/dev/null 2>&1; then
    packages+=(docker-compose-v2)
  fi
  if (( ${#packages[@]} == 0 )); then
    return 0
  fi

  require_command apt-get
  require_command apt-cache
  say "Refreshing Ubuntu package metadata before checking the Docker packages."
  apt-get update || fail "Could not refresh Ubuntu package metadata; Docker packages were not changed."
  for package in "${packages[@]}"; do
    apt-cache show "$package" >/dev/null 2>&1 || fail "Ubuntu package '$package' is unavailable in the current package catalog. No host changes have been made."
  done
  simulate_apt_install "${packages[@]}"
  say "Installing Ubuntu package(s): ${packages[*]}"
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${packages[@]}" || fail "Docker package installation failed. No packages were removed."
  if ! docker info >/dev/null 2>&1; then
    systemctl start docker || fail "Docker was installed but its service could not start."
  fi
  docker info >/dev/null 2>&1 || fail "Docker Engine is not responding after installation."
  docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin is unavailable after installation."
}

assert_ufw_ready_and_allow() {
  local status
  if (( EUID != 0 )); then
    warn "Skipping UFW configuration because this run is unprivileged. Ensure the host firewall allows TCP 8000 from $LAN_SUBNET; otherwise LAN clients may not reach the service."
    return 0
  fi
  command -v ufw >/dev/null 2>&1 || return 0
  status=$(ufw status) || fail "Could not read UFW status; refusing to change firewall rules."
  [[ "$status" == *"Status: active"* ]] || return 0
  if awk -v subnet="$LAN_SUBNET" '$0 ~ subnet && $0 ~ /8000\/tcp/ && $0 ~ /ALLOW IN/ { found=1 } END { exit !found }' <<< "$status"; then
    say "UFW already allows TCP 8000 from $LAN_SUBNET."
    return 0
  fi
  ufw allow from "$LAN_SUBNET" to any port 8000 proto tcp comment 'Speech to Text LAN service' || fail "Could not add the narrow UFW rule for $LAN_SUBNET."
}

check_health() {
  local container_id health state attempt
  container_id=$(docker compose -p "$COMPOSE_PROJECT" -f "$INSTALL_DIR/compose.yaml" ps -q speech-to-text)
  [[ -n "$container_id" ]] || fail "Compose did not create the Speech-to-Text container."
  for ((attempt = 1; attempt <= 60; attempt++)); do
    health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}missing{{end}}' "$container_id")
    state=$(docker inspect --format '{{.State.Status}}' "$container_id")
    [[ "$health" == "healthy" ]] && break
    [[ "$health" == "unhealthy" || "$state" == "exited" || "$health" == "missing" ]] && fail "Container did not become healthy (state=$state, health=$health). Inspect it with: docker logs $container_id"
    sleep 3
  done
  [[ "$health" == "healthy" ]] || fail "Container healthcheck did not pass within 180 seconds. Inspect it with: docker logs $container_id"
}

check_model_readiness() {
  local report
  if report=$(curl -fsS --max-time 20 "http://$LAN_IP:8000/api/v1/models" | python3 -c '
import json
import sys

try:
    payload = json.load(sys.stdin)
except Exception as exc:
    print(f"Could not parse model catalog JSON: {exc}", file=sys.stderr)
    raise SystemExit(1)
models = payload.get("models", []) if isinstance(payload, dict) else []
model = next((item for item in models if item.get("key") == "turbo"), None)
if not model or model.get("installed") is not True:
    print("The turbo model is not installed.", file=sys.stderr)
    raise SystemExit(1)
if payload.get("default_model") != "turbo" or payload.get("default_runtime") != "openvino-gpu":
    print("The configured model/runtime defaults are not turbo/openvino-gpu.", file=sys.stderr)
    raise SystemExit(1)
runtime = next((item for item in model.get("runtimes", []) if item.get("key") == "openvino-gpu"), None)
if not runtime or runtime.get("ready") is not True or "source" not in runtime.get("precision_options", []):
    print("The turbo OpenVINO GPU runtime is not ready with source precision available.", file=sys.stderr)
    raise SystemExit(1)
print("turbo is installed; openvino-gpu is ready with source precision available.")
'); then
    say "$report"
  else
    fail "Model readiness check failed. Inspect /api/v1/models and confirm turbo, openvino-gpu, and source precision are ready."
  fi
}

check_microphones() {
  local report
  if report=$(curl -fsS --max-time 20 "http://$LAN_IP:8000/api/v1/microphones" | python3 -c '
import json
import sys

try:
    payload = json.load(sys.stdin)
except Exception as exc:
    print(f"Could not parse microphone catalog JSON: {exc}", file=sys.stderr)
    raise SystemExit(1)
devices = payload.get("devices") if isinstance(payload, dict) else None
if not isinstance(devices, list):
    print("The microphone endpoint did not return a devices list.", file=sys.stderr)
    raise SystemExit(1)
if not devices:
    print("No microphone devices were discovered.", file=sys.stderr)
    raise SystemExit(1)
names = [str(device.get("name", "(unnamed)")) for device in devices]
print("Discovered {} microphone device(s): {}".format(len(devices), ", ".join(names)))
'); then
    say "$report"
  else
    fail "Microphone discovery failed or returned no devices. Check /dev/snd permissions and the host audio devices."
  fi
}

stage "Validate host"
[[ "$IMAGE_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "Image version must be a release tag such as v0.1.3."
[[ "$CHECKOUT_UID" =~ ^[0-9]+$ && "$CHECKOUT_GID" =~ ^[0-9]+$ ]] || fail "Could not determine the invoking checkout owner's numeric UID/GID."
[[ -r /etc/os-release ]] || fail "Cannot identify the operating system."
# shellcheck disable=SC1091
. /etc/os-release
[[ "${ID:-}" == ubuntu && "${VERSION_ID:-}" == 24.04 ]] || fail "This installer supports Ubuntu 24.04 only. No host changes have been made."
[[ "$(uname -m)" == x86_64 ]] || fail "This installer supports x86_64 only. No host changes have been made."
[[ -d /dev/dri ]] || fail "Intel GPU device directory /dev/dri is missing. No host changes have been made."
[[ -e /dev/dri/renderD128 || -n "$(find /dev/dri -maxdepth 1 -type c -name 'renderD*' -print -quit 2>/dev/null)" ]] || fail "No GPU render device exists under /dev/dri. No host changes have been made."
[[ -d /dev/snd ]] || fail "Audio device directory /dev/snd is missing. No host changes have been made."
for command_name in ip stat ss awk grep find head install; do require_command "$command_name"; done
require_command curl
require_command python3
detect_lan
render_device=$(find /dev/dri -maxdepth 1 -type c -name 'renderD*' -print -quit)
[[ -n "$render_device" ]] || fail "Could not locate a GPU render device under /dev/dri."
RENDER_GID=$(stat -c '%g' "$render_device")
AUDIO_GID=$(stat -c '%g' /dev/snd)
[[ "$RENDER_GID" =~ ^[0-9]+$ && "$AUDIO_GID" =~ ^[0-9]+$ ]] || fail "Could not detect numeric device group IDs."
port_is_free_or_owned
[[ ! -L "$INSTALL_DIR" ]] || fail "$INSTALL_DIR is a symbolic link; refusing to write outside the application directory."
[[ ! -e "$INSTALL_DIR" || -d "$INSTALL_DIR" ]] || fail "$INSTALL_DIR exists and is not a directory."
[[ ! -L "$PROJECT_DIR/data" ]] || fail "$PROJECT_DIR/data is a symbolic link; refusing to write installer state outside the checkout."
[[ ! -L "$INSTALL_DIR/data" ]] || fail "$INSTALL_DIR/data is a symbolic link; refusing to change ownership outside the application data directory."
for cache_path in "$CACHE_DIR" "$HF_CACHE_DIR" "$EXPORT_HOME_DIR" "$CACHE_DIR/xdg" "$EXPORT_XDG_CACHE_DIR" "$EXPORT_XDG_CONFIG_DIR" "$EXPORT_XDG_DATA_DIR" "$EXPORT_TMP_DIR"; do
  [[ ! -L "$cache_path" ]] || fail "$cache_path is a symbolic link; refusing to write installer cache outside the application directory."
done
[[ ! -L "$MODEL_DIR" ]] || fail "$MODEL_DIR is a symbolic link; refusing to write model files outside the checkout."
[[ ! -L "$INSTALL_DIR/compose.yaml" ]] || fail "$INSTALL_DIR/compose.yaml is a symbolic link; refusing to overwrite a file outside the application directory."
[[ -f "$SCRIPT_DIR/export_openvino_model.py" ]] || fail "The pinned model exporter is missing from $SCRIPT_DIR. Run the installer from a repository checkout."
if [[ -e "$INSTALL_DIR/compose.yaml" ]]; then
  [[ -f "$INSTALL_DIR/compose.yaml" ]] || fail "$INSTALL_DIR/compose.yaml exists and is not a regular file."
  grep -Fqx '# Managed by scripts/install_ubx330m.sh. Do not edit this file by hand.' "$INSTALL_DIR/compose.yaml" || fail "$INSTALL_DIR/compose.yaml has no installer management marker; refusing to overwrite a file created by something else."
fi
say "Host validated: Ubuntu 24.04 x86_64; LAN $LAN_IP/$LAN_IF ($LAN_SUBNET); render GID $RENDER_GID; audio GID $AUDIO_GID."

stage "Prepare Docker"
if command -v docker >/dev/null 2>&1; then
  if ! docker info >/dev/null 2>&1; then
    if (( EUID == 0 )) && command -v systemctl >/dev/null 2>&1; then
      systemctl start docker || fail "Docker is installed but the Engine could not be started."
    else
      fail "Docker is installed but the Engine is not running or this user cannot access it. Start Docker and grant this user access to its socket, then rerun."
    fi
  fi
fi
install_docker_if_needed
docker info >/dev/null 2>&1 || fail "Docker Engine is not responding."
docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin is not available."

stage "Prepare/load export dependencies"
say "Building the locked OpenVINO and Hugging Face dependencies into $EXPORT_DEPS_IMAGE from this checkout."
docker build --platform linux/amd64 --target python-deps --tag "$EXPORT_DEPS_IMAGE" \
  --file "$PROJECT_DIR/Dockerfile" "$PROJECT_DIR" \
  || fail "Could not build the local model export dependency image. The existing service, if any, was left running."

stage "Prepare model"
install -d -m 0755 "$INSTALL_DIR"
install -d -m 0755 \
  "$HF_CACHE_DIR" \
  "$EXPORT_HOME_DIR" \
  "$EXPORT_XDG_CACHE_DIR" \
  "$EXPORT_XDG_CONFIG_DIR" \
  "$EXPORT_XDG_DATA_DIR"
install -d -m 0700 "$EXPORT_TMP_DIR"
if (( EUID == 0 )); then
  chown "$CHECKOUT_UID:$CHECKOUT_GID" "$INSTALL_DIR"
  chown "$CHECKOUT_UID:$CHECKOUT_GID" \
    "$CACHE_DIR" \
    "$HF_CACHE_DIR" \
    "$EXPORT_HOME_DIR" \
    "$CACHE_DIR/xdg" \
    "$EXPORT_XDG_CACHE_DIR" \
    "$EXPORT_XDG_CONFIG_DIR" \
    "$EXPORT_XDG_DATA_DIR" \
    "$EXPORT_TMP_DIR"
fi
[[ ! -e "$MODEL_DIR" || -d "$MODEL_DIR" ]] || fail "$MODEL_DIR exists and is not a directory."
install -d -m 0755 "$MODEL_DIR"
if (( EUID == 0 )); then
  chown -R "$CHECKOUT_UID:$CHECKOUT_GID" "$MODEL_DIR"
fi
say "Checking or exporting the pinned turbo OpenVINO model into $MODEL_DIR."
docker run --rm --platform linux/amd64 --user "$CHECKOUT_UID:$CHECKOUT_GID" \
  --volume "$SCRIPT_DIR/export_openvino_model.py:/tmp/export_openvino_model.py:ro" \
  --volume "$MODEL_DIR:/models" \
  --volume "$CACHE_DIR:/cache" \
  --env HOME=/cache/home \
  --env HF_HUB_DISABLE_TELEMETRY=1 \
  --env HF_HOME=/cache/huggingface \
  --env XDG_CACHE_HOME=/cache/xdg/cache \
  --env XDG_CONFIG_HOME=/cache/xdg/config \
  --env XDG_DATA_HOME=/cache/xdg/data \
  --env TMPDIR=/cache/tmp \
  --env PYTHONDONTWRITEBYTECODE=1 \
  --entrypoint /build/.venv/bin/python "$EXPORT_DEPS_IMAGE" /tmp/export_openvino_model.py \
  --destination /models/openvino-turbo-source \
  || fail "Could not prepare the pinned OpenVINO model. The running service and existing model directory were left intact."

stage "Build application image"
say "Building $IMAGE locally from the current checkout for linux/amd64."
docker build --platform linux/amd64 --tag "$IMAGE" \
  --file "$PROJECT_DIR/Dockerfile" "$PROJECT_DIR" \
  || fail "Could not build the local application image. The running service, profile database, and model directory were left intact."

stage "Configure and start service"
port_is_free_or_owned
assert_ufw_ready_and_allow
install -d -m 0755 "$INSTALL_DIR"
install -d -m 0770 "$INSTALL_DIR/data"
if (( EUID == 0 )); then
  chown "$CHECKOUT_UID:$CHECKOUT_GID" "$INSTALL_DIR" "$INSTALL_DIR/data"
fi
chmod 0770 "$INSTALL_DIR/data"
cat > "$INSTALL_DIR/compose.yaml" <<COMPOSE
# Managed by scripts/install_ubx330m.sh. Do not edit this file by hand.
services:
  speech-to-text:
    image: $IMAGE
    ports:
      - "0.0.0.0:8000:8000"
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    group_add:
      - "$RENDER_GID"
      - "$AUDIO_GID"
      - "$CHECKOUT_GID"
    volumes:
      - $INSTALL_DIR/data:/data
      - $MODEL_DIR:/opt/models:ro
    environment:
      SPEECH_TO_TEXT_MODELS_DIR: /opt/models
      SPEECH_TO_TEXT_MODEL: turbo
      SPEECH_TO_TEXT_RUNTIME: openvino-gpu
      SPEECH_TO_TEXT_PRECISION: source
      SPEECH_TO_TEXT_PROFILE_DB: /data/profiles.sqlite3
    restart: unless-stopped
COMPOSE
if (( EUID == 0 )); then
  chown "$CHECKOUT_UID:$CHECKOUT_GID" "$INSTALL_DIR/compose.yaml"
fi

stage "Check readiness"
port_is_free_or_owned
docker compose -p "$COMPOSE_PROJECT" -f "$INSTALL_DIR/compose.yaml" --project-directory "$INSTALL_DIR" up -d --no-build || fail "Compose could not start the service. No unrelated containers were changed."
check_health
curl -fsS --max-time 5 "http://$LAN_IP:8000/healthz" >/dev/null || fail "The local HTTP health endpoint did not respond at http://$LAN_IP:8000/healthz."
check_model_readiness
check_microphones
printf '\n%s%s  Installation verified%s\n' "$BOLD" "$GREEN" "$RESET"
printf '  LAN URL: http://%s:8000\n' "$LAN_IP"
printf '  Local image: %s\n' "$IMAGE"
printf '  Data: %s/data (writable by container UID 10001 through GID %s)\n' "$INSTALL_DIR" "$CHECKOUT_GID"
printf '  Model: %s (mounted read-only at /opt/models)\n' "$MODEL_DIR"
printf '  LAN subnet detected: %s on %s\n' "$LAN_SUBNET" "$LAN_IF"
printf '  Normal go-live is still gated on completing and verifying outbound HTTP forwarding.\n\n'
