#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$PROJECT_DIR/data/ubx330m/compose.yaml"

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

if (( $# > 1 )); then
  fail "Usage: $0 [image-version]"
fi

[[ -f "$COMPOSE_FILE" && ! -L "$COMPOSE_FILE" ]] || fail "No installer-managed deployment found at $COMPOSE_FILE; run scripts/install_ubx330m.sh for a first-time install."
grep -Fqx '# Managed by scripts/install_ubx330m.sh. Do not edit this file by hand.' "$COMPOSE_FILE" || fail "$COMPOSE_FILE is not marked as installer-managed; refusing to update it."

git -C "$PROJECT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1 || fail "This command must run from a Git checkout."
branch=$(git -C "$PROJECT_DIR" symbolic-ref --quiet --short HEAD) || fail "The checkout is detached; switch to a branch with an upstream before updating."
upstream=$(git -C "$PROJECT_DIR" rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null) || fail "Branch '$branch' has no configured upstream. Configure one before updating."

if [[ -n "$(git -C "$PROJECT_DIR" status --porcelain --untracked-files=all)" ]]; then
  fail "The checkout is not clean; commit or remove local changes before updating."
fi

printf 'Fast-forwarding %s from %s...\n' "$branch" "$upstream"
git -C "$PROJECT_DIR" pull --ff-only || fail "Could not fast-forward from $upstream; the checkout was not updated."

if (( $# == 1 )); then
  exec "$SCRIPT_DIR/install_ubx330m.sh" "$1"
fi
exec "$SCRIPT_DIR/install_ubx330m.sh"
